name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "cd76f978fc93452e90b422a7c76dad78" },
  { binding = "SHARE", id = "284e533acc554859ba685d127227453e" }
]
